- name: Install bin files for client
  ansible.builtin.copy:
    src: "files_client/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
    - flood-init.sh
    - flood.sh
    - precache-flood.sh
    - notification-subscribe.sh
    - flood-artillery.sh

- name: Install etc files for client
  ansible.builtin.copy:
    src: "files_client/{{ item }}"
    dest: "/usr/local/etc/{{ item }}"
    owner: root
    group: root
    # writable by all!
    mode: u=rw,g=rw,o=rw
  loop:
    - flood.env
  register: client_etc_files

- name: Set default flood.env SOLID_FLOOD_USER_COUNT
  ansible.builtin.lineinfile:
    path: /usr/local/etc/flood.env
    regexp: '^SOLID_FLOOD_USER_COUNT='
    line: "SOLID_FLOOD_USER_COUNT={{ groups['ss_servers']|length * css_default_user_count }}"
  when: client_etc_files.changed

- name: Install list of server ATC URLs
  ansible.builtin.copy:
    content: |
      {% for host in groups['ss_servers'] %}http://{{ hostvars[host][ 'ansible_ssh_host' ] }}:8888/ {% endfor %}
    dest: /usr/local/etc/atc_urls
