- name: "Add redis apt key"
  ansible.builtin.apt_key:
    url: https://packages.redis.io/gpg
    state: present

- name: "Add redis ppa"
  ansible.builtin.apt_repository:
    repo: deb https://packages.redis.io/deb {{ ansible_distribution_release }} main
    update_cache: yes

- name: "Install redis"
  ansible.builtin.apt:
    update_cache: yes
    name: redis
    state: present
