- name: edit known hosts for gitlab.ilabt.imec.be
  ansible.builtin.known_hosts:
    name: gitlab.ilabt.imec.be
    key: gitlab.ilabt.imec.be,2001:6a8:1d80:26::203 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEwQdHxAolNADYrMfGq6k2uhJejbyQO61bDW9+TZWsLflObuCd7m9mKSHpA4l2jjoebNPV4fnYA/PlaCRVovj14=
    path: /etc/ssh/ssh_known_hosts

- name: edit known hosts for github.ugent.be
  ansible.builtin.known_hosts:
    name: github.ugent.be
    key: github.ugent.be,157.193.230.57 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIj+/vbfBHjUb1kRsdG+TxKBY0RLOYn6aZNGDpneB6X+1QFgfXLO+u6RiwM0cmQftHpswDxbpzdbq1epVld8zP8=
    path: /etc/ssh/ssh_known_hosts

- name: edit known hosts for github.com
  ansible.builtin.known_hosts:
    name: github.com
    key: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    path: /etc/ssh/ssh_known_hosts
