---
- hosts: css_servers
  become: yes
  vars_files:
    - ansible-variables.yaml
  roles:
    - common
    - fqdn
    - github_known_hosts
    - python
    - perfstat
    - nodejs
    - css_populate
    - css_flood
    - certbot
    - redis
    - setup_css_script
  tasks:
#    - name: Print all available facts
#      ansible.builtin.debug:
#        var: ansible_facts

#    - name: Print hostvars
#      ansible.builtin.debug:
#        var: hostvars

    - name: Check if https is possible
      ansible.builtin.fail:
        msg: If https is required, the host needs a valid FQDN
      when: ( css_use_https and not has_fqdn )

#    - name: Check python version
#      ansible.builtin.fail:
#        msg: "The system python version {{ ansible_facts['python_version' ]}} is too old. Python 3.11 or newer is required."
#      when: (ansible_facts['python']['version']['major'] != 3) or (ansible_facts['python']['version']['minor'] < 11)

#    - name: Set an ID for the node in /etc/nickname
#      ansible.builtin.copy:
#        content: test
#        dest: /etc/nickname

    # Start CSS

    - name: Start CSS
      shell: setup_css.sh
      when: start_css
      timeout: "{{ 20 * 60 }}"
      environment:
        CSS_PUBLIC_DNS_NAME: "{{ '' if css_use_https else 'localhost' }}"
    # setup_css.sh writes to /usr/local/share/css_url

    - name: Collect server URLs
      ansible.builtin.fetch:
        src: /usr/local/share/css_url
        dest: css_url_{{ inventory_hostname }}
        flat: yes
      when: start_css
