---
- hosts: all
  become: yes
  vars_files:
    - ansible-variables.yaml
  tasks:
#    - name: Print all available facts
#      ansible.builtin.debug:
#        var: ansible_facts

#    - name: Print hostvars
#      ansible.builtin.debug:
#        var: hostvars

    - name: Find system FQDN (if any)
      ansible.builtin.set_fact:
        # Check if a usable FQDN is available (not a bare IPv4 or IPv6 and not "localhost")
        # Prefer FQDN from inventory ansible_ssh_host, use ansible_facts['fqdn'] as fallback
        inv_chosen_fqdn: "{{ hostvars[ inventory_hostname ][ 'ansible_ssh_host' ] }}"

    - name: Find system FQDN (if any)
      ansible.builtin.set_fact:
        inv_has_fqdn: "{{ not not( ( inv_chosen_fqdn | regex_search('^.*\\..*') ) and (inv_chosen_fqdn != 'localhost') and ( not ( inv_chosen_fqdn | regex_search('^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+') ) ) and ( not ( inv_chosen_fqdn | regex_search(':') ) ) ) }}"

    - name: Find system FQDN (if any)
      ansible.builtin.set_fact:
        facts_chosen_fqdn: "{{ ansible_facts['fqdn'] }}"

    - name: Find system FQDN (if any)
      ansible.builtin.set_fact:
        facts_has_fqdn: "{{ not not( (facts_chosen_fqdn) and ( facts_chosen_fqdn | regex_search('^.*\\..*') ) and (facts_chosen_fqdn != 'localhost') and ( not ( facts_chosen_fqdn | regex_search('^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+') ) ) and ( not ( facts_chosen_fqdn | regex_search(':') ) ) ) }}"

    - name: Find system FQDN (if any)
      ansible.builtin.set_fact:
        chosen_fqdn: "{{ inv_chosen_fqdn if inv_has_fqdn else facts_chosen_fqdn }}"

    - name: Find system FQDN (if any)
      ansible.builtin.set_fact:
        has_fqdn: "{{ inv_has_fqdn or facts_has_fqdn }}"

    - name: Print system info
      ansible.builtin.debug:
        msg: |
           System '{{ inventory_hostname }}'
              has_fqdn {{ has_fqdn }}
              chosen_fqdn '{{ chosen_fqdn }}'
              ansible_ssh_host '{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}'
              ansible_facts fqdn '{{ ansible_facts['fqdn'] }}'
              ansible_facts hostname '{{ ansible_facts['hostname'] }}'

    - name: Check if https is possible
      ansible.builtin.fail:
        msg: If https is required, the host needs a valid FQDN
      when: ( css_use_https and not has_fqdn )

    - name: Check python version
      ansible.builtin.fail:
        msg: "The system python version {{ ansible_facts['python_version' ]}} is too old. Python 3.11 or newer is required."
      when: (ansible_facts['python']['version']['major'] != 3) or (ansible_facts['python']['version']['minor'] < 11)

    - name: Store system FQDN in /etc/host_fqdn
      # This way, all scripts always have this easily available
      ansible.builtin.copy:
        content: "{{ chosen_fqdn }}"
        dest: /etc/host_fqdn
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      when: ( has_fqdn )

    - name: Prevent NetworkManager from being installed
      ansible.builtin.copy:
        content: |
          Package: network-manager
          Pin: release *
          Pin-Priority: -1
        dest: /etc/apt/preferences.d/no-network-manager

    - name: Install utils
      ansible.builtin.apt:
        pkg: [ 'git', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'openssl', 'wget', 'gnupg', 'tmux', 'vim', 'build-essential', 'ncdu', 'lsb-release', 'jq']
        update_cache: yes

    - name: Prevent systemd from filling /var/log/syslog
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        state: present
        regexp: '^ForwardToSyslog=no'
        line: 'ForwardToSyslog=no'

    - name: Install xterm-kitty terminfo
      ansible.builtin.get_url:
        url: https://github.com/kovidgoyal/kitty/raw/master/terminfo/x/xterm-kitty
        dest: /usr/share/terminfo/x/xterm-kitty
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Set an ID for the node in /etc/nickname
      ansible.builtin.copy:
        content: test
        dest: /etc/nickname

    - name: edit known hosts for gitlab.ilabt.imec.be
      ansible.builtin.known_hosts:
        name: gitlab.ilabt.imec.be
        key: gitlab.ilabt.imec.be,2001:6a8:1d80:26::203 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEwQdHxAolNADYrMfGq6k2uhJejbyQO61bDW9+TZWsLflObuCd7m9mKSHpA4l2jjoebNPV4fnYA/PlaCRVovj14=
        path: /etc/ssh/ssh_known_hosts

    - name: edit known hosts for github.ugent.be
      ansible.builtin.known_hosts:
        name: github.ugent.be
        key: github.ugent.be,157.193.230.57 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIj+/vbfBHjUb1kRsdG+TxKBY0RLOYn6aZNGDpneB6X+1QFgfXLO+u6RiwM0cmQftHpswDxbpzdbq1epVld8zP8=
        path: /etc/ssh/ssh_known_hosts

    - name: edit known hosts for github.com
      ansible.builtin.known_hosts:
        name: github.com
        key: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        path: /etc/ssh/ssh_known_hosts

    - name: Set timezone to Europe/Brussels
      community.general.timezone:
        name: Europe/Brussels

    - name: Install python
      ansible.builtin.apt:
        pkg:
          - python3
          - pip
          - python3-venv
        update_cache: yes

    - name: Create /usr/local/venv/
      ansible.builtin.file:
        path: /usr/local/venv/
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: clone solidlab-perfstat
      ansible.builtin.git:
        repo: https://github.com/SolidLabResearch/solidlab-perfstat.git
        dest: /usr/local/src/solidlab-perfstat
      when: install_perfstat

    - name: Setup venv with solidlab-perfstat
      ansible.builtin.pip:
        name:
          - file:///usr/local/src/solidlab-perfstat/
        virtualenv_command: '/usr/bin/python3 -m venv'
        virtualenv: /usr/local/venv/solidlab-perfstat/
      when: install_perfstat

    - name: Install perfstat Systemd Services
      ansible.builtin.copy:
        src: "files_css/perfstat.service"
        dest: "/etc/systemd/system/perfstat.service"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      when: install_perfstat

    # TODO setup perfstart service and start it
    # exe in /usr/local/venv/solidlab-perfstat/bin/solidlab-perfstat
    # create /etc/perfstat.env ?

    - name: "Add nodejs apt key"
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: "Add nodejs 16.x ppa for apt repo"
      ansible.builtin.apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main
        update_cache: yes

    - name: Prefer deb.nodesource.com over official
      ansible.builtin.copy:
        content: |
          Package: nodejs
          Pin: origin "deb.nodesource.com"
          Pin-Priority: 1001
        dest: /etc/apt/preferences.d/prefer-nodesource

    - name: "Install nodejs 16"
      ansible.builtin.apt:
        name:
          - nodejs
        state: present

    - name: Fetch nodejs version
      ansible.builtin.shell: 'node --version'
      register: nodejs_version

    - name: Check nodejs version
      ansible.builtin.fail:
        msg: "The nodejs version install {{ nodejs_version }} is not the expected version 16."
      when: (not (nodejs_version.stdout | regex_search("^16."))) and (not (nodejs_version.stdout | regex_search("^v16.")))

    - name: Install "typescript" node.js package.
      community.general.npm:
        name: typescript
        global: true
        path: /usr/local/

    - name: "Install relaxed-json"
      # rjson is the cli tool of relaxed-json. See https://github.com/phadej/relaxed-json
      # see also https://github.com/jqlang/jq/wiki/FAQ#processing-not-quite-valid-json
      # this is used to manipulate CSS config, even when it is not strict json  (mostly trailing comma's)
      community.general.npm:
        global: true
        name: relaxed-json
        path: /usr/local/

    - name: "Install snapd"
      ansible.builtin.apt:
        name: snapd
      when: css_use_https

    - name: Install snap core
      community.general.snap:
        name: core
      when: css_use_https

    - name: Install certbot
      community.general.snap:
        name: certbot
        classic: true
      when: css_use_https

    - name: Link certbot exe
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/local/bin/certbot
        owner: root
        group: root
        state: link
      when: css_use_https

    - name: Install Exe provide_certs.sh
      ansible.builtin.copy:
        src: "files_css/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      loop:
        - provide_certs.sh
      when: css_use_https

    - name: Install Exe setup_css.sh
      ansible.builtin.copy:
        src: "files_css/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      loop:
        - setup_css.sh

    - name: Install setup_css.env
      ansible.builtin.copy:
        src: "files_css/setup_css.env"
        dest: "/usr/local/etc/setup_css.env"
        owner: root
        group: root
        # writable by all!
        mode: u=rw,g=rw,o=rw

    - name: Install css Systemd Services
      ansible.builtin.copy:
        src: "files_css/css.service"
        dest: "/etc/systemd/system/css.service"
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Install Template Systemd Service for css
      ansible.builtin.copy:
        src: "files_css/css.service.template"
        dest: "/etc/systemd/system/css.service.template"
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Install auth-cache-webserver Systemd Services
      ansible.builtin.copy:
        src: "files_css/auth-cache-webserver.service"
        dest: "/etc/systemd/system/auth-cache-webserver.service"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      when: start_auth_cache_webserver

    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true

    # install_css_populate.sh

    - name: clone css-populate
      ansible.builtin.git:
        repo: https://github.com/SolidLabResearch/css-populate.git
        dest: /usr/local/src/css-populate
      when: install_server_css_populate

    - name: "Install css-populate"
      community.general.npm:
        global: true
        path: /usr/local/src/css-populate
      when: install_server_css_populate

    - name: 'Copy dummy RDF'
      ansible.builtin.copy:
        src: "files_all/infobox-properties_lang=nl__head75000_10MB.nt.gz"
        dest: "/usr/local/share/infobox-properties_lang=nl__head75000_10MB.nt.gz"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      when: install_server_css_populate

    - name: 'Decompress dummy RDF'
      ansible.builtin.shell: |
        #!/bin/bash -e
        
        gzip --to-stdout -d "infobox-properties_lang=nl__head75000_10MB.nt.gz" > "infobox-properties_lang=nl__head75000_10MB.nt"
        head -n 7500 "infobox-properties_lang=nl__head75000_10MB.nt" > "infobox-properties_lang=nl__head7500_1MB.nt"
        head -n 750 "infobox-properties_lang=nl__head75000_10MB.nt" > "infobox-properties_lang=nl__head750_100kB.nt"
      args:
        chdir: /usr/local/share/
        creates: /usr/local/share/infobox-properties_lang=nl__head75000_10MB.nt
      when: install_server_css_populate

    # install_redis.sh

    - name: "Add redis apt key"
      ansible.builtin.apt_key:
        url: https://packages.redis.io/gpg
        state: present

    - name: "Add redis ppa"
      ansible.builtin.apt_repository:
        repo: deb https://packages.redis.io/deb {{ ansible_distribution_release }} main
        update_cache: yes

    - name: "Install redis"
      ansible.builtin.apt:
        update_cache: yes
        name: redis
        state: present

    # install_flood.sh  (needed for auth cache, which is then shared by auth-cache-webservice)

    - name: clone css-flood
      ansible.builtin.git:
        repo: https://github.com/SolidLabResearch/css-flood.git
        dest: /usr/local/src/css-flood
      when: install_server_css_flood

    - name: Install css-flood
      community.general.npm:
        global: true
        path: /usr/local/src/css-flood
      when: install_server_css_flood

    # Start CSS

    - name: Set defaults in setup_css.env
      ansible.builtin.lineinfile:
        path: /usr/local/etc/setup_css.env
        regexp: '^GIT_CHECKOUT_ARG='
        line: GIT_CHECKOUT_ARG={{ css_default_checkout_arg }}

    - name: Set defaults in setup_css.env
      ansible.builtin.lineinfile:
        path: /usr/local/etc/setup_css.env
        regexp: '^GENERATE_USERS='
        line: GENERATE_USERS={{ css_default_generate_users }}

    - name: Set defaults in setup_css.env
      ansible.builtin.lineinfile:
        path: /usr/local/etc/setup_css.env
        regexp: '^GENERATE_CONTENT='
        line: GENERATE_CONTENT={{ css_default_generate_content }}

    - name: Set defaults in setup_css.env
      ansible.builtin.lineinfile:
        path: /usr/local/etc/setup_css.env
        regexp: '^SERVER_FACTORY='
        line: SERVER_FACTORY={{ 'https' if css_use_https else 'http' }}

    - name: Start CSS
      shell: setup_css.sh
      when: start_css
      timeout: "{{ 20 * 60 }}"
