---
- hosts: all
  become: yes
  tasks:
    - name: Prevent NetworkManager from being installed
      ansible.builtin.copy:
        content: | 
          Package: network-manager
          Pin: release *
          Pin-Priority: -1
        dest: /etc/apt/preferences.d/no-network-manager
    
    - name: Install utils 
      ansible.builtin.apt:
        pkg: [ 'git', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'openssl', 'wget', 'gnupg', 'tmux', 'vim', 'build-essential', 'ncdu', 'lsb-release', 'jq']
        update_cache: yes
    
    - name: Prevent systemd from filling /var/log/syslog
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        state: present
        regexp: '^ForwardToSyslog=no'
        line: 'ForwardToSyslog=no'
    
    - name: Install xterm-kitty terminfo
      ansible.builtin.get_url: 
         url: https://github.com/kovidgoyal/kitty/raw/master/terminfo/x/xterm-kitty
         dest: /usr/share/terminfo/x/xterm-kitty
         owner: root
         group: root
         mode: u=rw,g=r,o=r
    
    - name: Set an ID for the node in /etc/nickname
      ansible.builtin.copy:
        content: test
        dest: /etc/nickname

    - name: edit known hosts for gitlab.ilabt.imec.be
      ansible.builtin.known_hosts:
        name: gitlab.ilabt.imec.be
        key: gitlab.ilabt.imec.be,2001:6a8:1d80:26::203 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEwQdHxAolNADYrMfGq6k2uhJejbyQO61bDW9+TZWsLflObuCd7m9mKSHpA4l2jjoebNPV4fnYA/PlaCRVovj14=
        path: /etc/ssh/ssh_known_hosts

    - name: edit known hosts for github.ugent.be
      ansible.builtin.known_hosts:
        name: github.ugent.be
        key: github.ugent.be,157.193.230.57 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIj+/vbfBHjUb1kRsdG+TxKBY0RLOYn6aZNGDpneB6X+1QFgfXLO+u6RiwM0cmQftHpswDxbpzdbq1epVld8zP8=
        path: /etc/ssh/ssh_known_hosts

    - name: edit known hosts for github.com
      ansible.builtin.known_hosts:
        name: github.com
        key: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        path: /etc/ssh/ssh_known_hosts

    - name: Set timezone to Europe/Brussels
      community.general.timezone:
        name: Europe/Brussels

    - name: Install python
      ansible.builtin.apt:
        pkg:
          - python3
          - pip
          - python3-venv
        update_cache: yes

    - name: Create /usr/local/venv/
      ansible.builtin.file:
        path: /usr/local/venv/
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: clone solidlab-perfstat
      ansible.builtin.git:
        repo: https://github.com/SolidLabResearch/solidlab-perfstat.git
        dest: /usr/local/src/solidlab-perfstat

    - name: Setup venv with solidlab-perfstat
      ansible.builtin.pip:
        name:
          - file:///usr/local/src/solidlab-perfstat/
        virtualenv_command: '/usr/bin/python3 -m venv'
        virtualenv: /usr/local/venv/solidlab-perfstat/
