---
- hosts: ss_servers
  become: yes
  vars_files:
    - ansible-variables.yaml
  roles:
    - role: common
      tags: setup
    - role: fqdn
      tags: setup
    - role: github_known_hosts
      tags: setup
    - role: python
      tags: setup
    - role: perfstat
      tags: setup
    - role: nodejs
      tags: setup
    - role: css_populate
      tags: setup
    - role: css_flood
      tags: setup
    - role: docker
      when: ss_type == 'kss'
      tags: setup
    - role: certbot
      when: ss_type == 'css'
      tags: setup
    - role: redis
      when: ss_type == 'css'
      tags: setup
    - role: setup_css_script
      when: ss_type == 'css'
      tags: css
    - role: install_kss
      when: ss_type == 'kss'
      tags: kss
  tasks:
#    - name: Print all available facts
#      ansible.builtin.debug:
#        var: ansible_facts

#    - name: Print hostvars
#      ansible.builtin.debug:
#        var: hostvars

    - name: Check if https is possible
      ansible.builtin.fail:
        msg: If https is required, the host needs a valid FQDN
      when: ( ss_use_https and not has_fqdn )
      tags: setup

#    - name: Set an ID for the node in /etc/nickname
#      ansible.builtin.copy:
#        content: test
#        dest: /etc/nickname

    # Start CSS

    - name: Start CSS
      shell: setup_css.sh
      when: ( start_ss and ss_type == 'css' )
      timeout: "{{ 20 * 60 }}"
      environment:
        CSS_PUBLIC_DNS_NAME: "{{ '' if ss_use_https else 'localhost' }}"
      tags: css
    # setup_css.sh writes to /usr/local/share/ss_url

    - name: Collect server URLs
      ansible.builtin.fetch:
        src: /usr/local/share/ss_url
        dest: ss_url_{{ inventory_hostname }}
        flat: yes
      when: start_ss
      tags: post
