- name: Check nodejs version
  ansible.builtin.fail:
    msg: "The nodejs version requested {{ nodejs_version }} is not the supported by this role."
  when: (nodejs_version != 16) and (nodejs_version != 18)

- name: "Add nodesource key"
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodesource repo key"
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present

- name: "Add nodejs {{ nodejs_version }}.x ppa for apt repo"
  ansible.builtin.apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main
    update_cache: yes

- name: Prefer deb.nodesource.com over official
  ansible.builtin.copy:
    content: |
      Package: nodejs
      Pin: origin "deb.nodesource.com"
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/prefer-nodesource

- name: "Install nodejs {{ nodejs_version }}"
  ansible.builtin.apt:
    name:
      - nodejs
    state: latest
#    state: present

- name: Fetch nodejs version
  ansible.builtin.shell: 'node --version'
  register: actual_nodejs_version

- name: Check nodejs version 16
  ansible.builtin.fail:
    msg: "The nodejs version installed {{ actual_nodejs_version.stdout }} is not the expected version {{ nodejs_version }}."
  when: ((nodejs_version == 16) and (not (actual_nodejs_version.stdout | regex_search("^16."))) and (not (actual_nodejs_version.stdout | regex_search("^v16."))))

- name: Check nodejs version 18
  ansible.builtin.fail:
    msg: "The nodejs version installed {{ actual_nodejs_version.stdout }} is not the expected version {{ nodejs_version }}."
  when: ((nodejs_version == 18) and (not (actual_nodejs_version.stdout | regex_search("^18."))) and (not (actual_nodejs_version.stdout | regex_search("^v18."))))

- name: Install "typescript" node.js package.
  community.general.npm:
    name: typescript
    global: true
    path: /usr/local/
