# install_flood.sh  (on the css server machine this is needed for auth cache, which is then shared by auth-cache-webservice)
- name: clone css-flood
  ansible.builtin.git:
    repo: https://github.com/SolidLabResearch/css-flood.git
    dest: /usr/local/src/css-flood
  when: install_server_css_flood

- name: Install css-flood
  community.general.npm:
    path: /usr/local/src/css-flood
  when: install_server_css_flood

- name: "Build and link css-flood"
  ansible.builtin.shell: |
    #!/bin/bash -e
    cd /usr/local/src/css-flood
    npm run build
    npm config set prefix "/usr/local"
    npm link
